// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjdkwhkkiftzpiislnrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqZGt3aGtraWZ0enBpaXNsbnJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjM1NjMsImV4cCI6MjA2OTY5OTU2M30.OfP6WLDlvv3VXFprPiUPEFlr7O-TI73Nfp5Z-__HTs0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});